### PR TITLE
Fix several public facing routes

### LINKED ISSUE #1422: Going to public post using group URL should show the post
Going to a public post when not logged in using the group URL (e.g. https://www.hylo.com/groups/openteam/post/55661) should redirect to https://www.hylo.com/post/55661 and show the post, but instead it redirects to the public map

### PR DESCRIPTION
**Pull request by thomasgwatson**
There were a couple of public routes that were either inaccessible or their styling wasn't displaying correctly.

Closes #1422

### CODE REVIEW

File: src/routes/PublicLayoutRouter/PublicLayoutRouter.js [hunk 1]
```diff
@@ -28,9 +28,10 @@ export default function PublicLayoutRouter (props) {
         <Route path={`/${POST_DETAIL_MATCH}`} exact component={PublicPostDetail} />
         <Route path='/:context(groups)/:groupSlug' exact component={PublicGroupDetail} />
         <Route path='/:context(public)/:view(map)' component={MapExplorerLayoutRouter} />
-        <Route path='/:context(public)/:view(groups)' exact component={GroupExplorerLayoutRouter} />
+        <Route path='/:context(public)/:view(groups)(.*)' exact component={GroupExplorerLayoutRouter} />
```
Comment (lorenjohnson) [inline src/routes/PublicLayoutRouter/PublicLayoutRouter.js:31]: Did you try removing `exact`? I think that would do the same thing and be more idiomatic.

File: src/routes/PublicLayoutRouter/PublicLayoutRouter.js [hunk 2]
```diff
@@ -28,9 +28,10 @@ export default function PublicLayoutRouter (props) {
...
         {/* Remove this once we show the public stream */}
         <Redirect exact from={`/public/${POST_DETAIL_MATCH}`} to='/post/:postId' />
+        <Redirect exact from={`/:context(groups)/:groupSlug/:view(events|groups|map|members|projects|settings|stream|topics|custom)/${POST_DETAIL_MATCH}`} to='/post/:postId' />
```
Comment (lorenjohnson) [inline src/routes/PublicLayoutRouter/PublicLayoutRouter.js:34]: It may be a small rabbithole, but one I want us to keep an eye one as this I think is the case: This I think can be just `(.*)/${POST_DETAIL_MATCH}` and not break anything. Try it if you don't mind, and I am sorry ahead of time if I've missed something.

File: src/routes/PublicLayoutRouter/PublicLayoutRouter.js [hunk 3]
```diff
@@ -133,7 +136,9 @@ export function GroupExplorerLayoutRouter () {
   return (
     <>
       <div styleName='center-column' id={CENTER_COLUMN_ID}>
-        <GroupExplorer />
+        <div>
```
Comment (lorenjohnson) [inline src/routes/PublicLayoutRouter/PublicLayoutRouter.js:139]: Curious why the extra `div` fixed things here? It's nitpick a bit, but not a fan of extra containers unless they're truly necessary, in most all cases I find that adjusting the flex box layout of the existing container is good enough?

**Review by lorenjohnson — CHANGES_REQUESTED** [review]
Don't stress it, but would be nice to hear back on these few things. And glad you're getting to this stuff!

File: src/routes/PublicLayoutRouter/PublicLayoutRouter.js (hunk 3 above)
Comment (thomasgwatson) [reply src/routes/PublicLayoutRouter/PublicLayoutRouter.js:137]: The whole complexity of the auth styling for this, with the nav div, the center div and the detail div, have not been ported over. This was an extra fix, beyond the scope of this ticket, just to have things looking vaguely correct.

**Review by lorenjohnson — APPROVED** [review]
I haven't QA'd through to test the routes, assume you did, and the code looks good👍🏼

File: src/routes/PublicLayoutRouter/PublicLayoutRouter.js [hunk 4]
```diff
@@ -28,9 +28,8 @@ export default function PublicLayoutRouter (props) {
         <Route path={`/${POST_DETAIL_MATCH}`} exact component={PublicPostDetail} />
         <Route path='/:context(groups)/:groupSlug' exact component={PublicGroupDetail} />
         <Route path='/:context(public)/:view(map)' component={MapExplorerLayoutRouter} />
-        <Route path='/:context(public)/:view(groups)' exact component={GroupExplorerLayoutRouter} />
-        {/* Remove this once we show the public stream */}
-        <Redirect exact from={`/public/${POST_DETAIL_MATCH}`} to='/post/:postId' />
+        <Route path='/:context(public)/:view(groups)' component={GroupExplorerLayoutRouter} />
+        <Redirect from={`(.*)/${POST_DETAIL_MATCH}`} to='/post/:postId' />
```
Comment (tibetsprague) [inline src/routes/PublicLayoutRouter/PublicLayoutRouter.js:32]: won't this break trying to look at a post from the public map? it will redirect to /post/id

File: src/routes/PublicLayoutRouter/PublicLayoutRouter.js (hunk 2 above)
Comment (tibetsprague) [reply src/routes/PublicLayoutRouter/PublicLayoutRouter.js]: won't this make it not possible to view posts from the public map though? /public/map/post/:id will redirect to /post/:id

File: src/routes/PublicLayoutRouter/PublicLayoutRouter.js (hunk 4 above)
Comment (thomasgwatson) [reply src/routes/PublicLayoutRouter/PublicLayoutRouter.js:32]: any public/map/post/:postId routes will be caught and forwarded to the 'MapExplorerLayoutRouter' before this redirect is invoked. AND... the mapExplorer is wonky after the routing shifts, which I am now addressing in the context of the map not rendering.

Comment (tibetsprague) [reply src/routes/PublicLayoutRouter/PublicLayoutRouter.js:32]: ok cool
