### PR TITLE
Fix for dup post change of type losing content

### LINKED ISSUE #1610: Changing post type of duplicated post before saving it loses all content
because changing the post type changes the URL and gets rid of the fromPostId= parameter

### PR DESCRIPTION
**Pull request by KevinTriplett**
Fixes #1610:

- Preserve `fromPostId` in search query param string for duplicated posts while editing
- Adds new function `setQuerystringParam` to support this preservation
- No new tests added (requiresintegration test?)

### CODE REVIEW

File: src/components/PostEditor/PostEditor.js [hunk 1]
```diff
@@ -27,6 +27,7 @@ import { PROJECT_CONTRIBUTIONS } from 'config/featureFlags'
 import { MAX_POST_TOPICS } from 'util/constants'
 import { sanitizeURL } from 'util/url'
 import Tooltip from 'components/Tooltip'
+import setQuerystringParam from 'store/selectors/setQuerystringParam'
```
Comment (tibetsprague) [inline src/components/PostEditor/PostEditor.js:30]: this is not a selector. selectors are just about getting data. we already have a function util/navigation.js#addQuerystringToPath which does almost this. you can tweak it to support no path, or add another function to util/navigation.js

**Review by tibetsprague — CHANGES_REQUESTED** [review]

File: src/components/PostEditor/PostEditor.js (hunk 1 above)
Comment (KevinTriplett) [reply src/components/PostEditor/PostEditor.js:30]: Doh! Thanks for pointing me to the right category :)

Comment (KevinTriplett) [reply src/components/PostEditor/PostEditor.js]: Okay, moved the function to util/navigation.js as addQuerystringToPath would have been kinda mangled by this feature.

**Review by tibetsprague — APPROVED** [review]
👍
