### PR TITLE
Better handle broken invite links for logged in users

### LINKED ISSUE #1260: Handle broken invite links better

### PR DESCRIPTION
**Pull request by thomasgwatson**
Closes #1260 

This issue only showed up for logged in users; non-logged in folk already got clear instructions as to the issue at hand.

### CODE REVIEW

File: src/routes/JoinGroup/JoinGroup.js [hunk 1]
```diff
@@ -56,7 +55,8 @@ export default function JoinGroup (props) {
           }
         }
       } catch (error) {
-        history.goBack()
+        window.alert('Sorry, your invitation to this group is expired, has already been used, or invalid. Please contact a group moderator for another one.')
```
Comment (tibetsprague) [inline src/routes/JoinGroup/JoinGroup.js:58]: "or is invalid" (missing an is)

**Review by tibetsprague — APPROVED** [review]

File: src/routes/JoinGroup/JoinGroup.js (hunk 1 above)
Comment (thomasgwatson) [reply src/routes/JoinGroup/JoinGroup.js:58]: Grabbed it from elsewhere in the app, I'll update both ;)
