### PR TITLE
Evo 935 event invite infinite scroll

### LINKED ISSUE #935: Event suggested invites list not showing all members, only first few, search broken too
The suggested people to invite only shows a short list, you should be able to scroll it to load more people

### PR DESCRIPTION
**Pull request by thomasgwatson**
Closes #935

### CODE REVIEW

File: src/components/EventInviteDialog/EventInviteDialog.js [hunk 1]
```diff
@@ -7,102 +7,116 @@ import Button from 'components/Button'
...
-  onSearchChange = ({ target: { value } }) => {
-    const { fetchPeople, forGroups } = this.props
-    const forGroupIds = forGroups.map(c => c.id)
-    this.setState({ searchTerm: value })
-    fetchPeople(value, forGroupIds)
-  }
+  const { observe } = useInView({
+    onEnter: () => {
+      const fetch = () => {
+        const forGroupIds = forGroups.map(c => c.id)
```
Comment (tibetsprague) [inline src/components/EventInviteDialog/EventInviteDialog.js:46]: isnt this basically a duplicate function of the one above? could pull out and reuse

**Review by tibetsprague — APPROVED** [review]
one little thing, but otherwise looks good!

File: src/components/EventInviteDialog/EventInviteDialog.js (hunk 1 above)
Comment (thomasgwatson) [reply src/components/EventInviteDialog/EventInviteDialog.js:46]: the two `fetch` functions overall or the `forGroupIds`
