### PR TITLE
Added various instructional messages and small fixes

### LINKED ISSUE #1552: Instructional message when adding topics
When folks try to add topics with a space between (Ex: #product design), there should be a popup or instructions that there cannot be a space between (or emphasizing to include a hyphen). If folks try to add a topic with a space, there is no way for them to create the post

### PR DESCRIPTION
**Pull request by thomasgwatson**
Closes #1552 #1553 #1554 #1556 

Screenshot 2023-11-06 at 8 51 09 AM
Screenshot 2023-11-06 at 8 50 33 AM
Screenshot 2023-11-06 at 8 50 07 AM

### CODE REVIEW

File: src/components/HyloEditor/HyloEditor.js [hunk 1]
```diff
@@ -149,7 +149,7 @@ const HyloEditor = React.forwardRef(function HyloEditor ({
       return editorRef.current.getText()
     },
     isEmpty: () => {
-      return editorRef.current.isEmpty
+      return editorRef.current?.isEmpty
```
Comment (tibetsprague) [inline src/components/HyloEditor/HyloEditor.js:152]: wait, shouldnt editorRef.current being not existent return true? so in that case it would be editorRef.current ? editorRef.current.isEmpty : true

File: src/routes/PostDetail/Comments/CommentForm/CommentForm.js [hunk 2]
```diff
@@ -51,11 +52,12 @@ class CommentForm extends Component {
...
       sendIsTyping,
       attachments,
-      clearAttachments
+      clearAttachments,
+      t
     } = this.props
 
     if (this.editor?.current && this.editor.current.isEmpty()) {
-      // Do nothing and stop event propagation
+      window.alert(t('You need to include text to post a comment'))
```
Comment (tibetsprague) [inline src/routes/PostDetail/Comments/CommentForm/CommentForm.js:60]: you know, it seems like we should allow comments that are just images... but maybe thats another ticket. I could also see this one being kind of annoying. I dont think anyone would expect that hitting enter with an empty comment would do anything, but now it pops up a window alert you have to close. maybe we only do an alert if there's an image but no text? or maybe we just change it so that if there's an image but no text we set the comment text to a blank space and let it be created?

**Comment by tibetsprague** [comment]
where's the part about telling people they must add a Title to a post?

**Comment by thomasgwatson** [comment]
> where's the part about telling people they must add a Title to a post?

Actually covered in another PR.

File: src/components/HyloEditor/HyloEditor.js (hunk 1 above)
Comment (thomasgwatson) [reply src/components/HyloEditor/HyloEditor.js:152]: With the other changes here, there is a moment in its lifecycle where `editorRef.current` is null or undefined when this.editor.current.isEmpty() is called, and so it errors.

File: src/routes/PostDetail/Comments/CommentForm/CommentForm.js (hunk 2 above)
Comment (thomasgwatson) [reply src/routes/PostDetail/Comments/CommentForm/CommentForm.js:60]: Ok, changed this to allow comment posts with just images.

File: src/components/HyloEditor/HyloEditor.js (hunk 1 above)
Comment (tibetsprague) [reply src/components/HyloEditor/HyloEditor.js:152]: I get that, it just seems like for isEmpty to return the correct value (which should be true in that case) then it needs to be rewritten as I suggested

Comment (thomasgwatson) [reply src/components/HyloEditor/HyloEditor.js:152]: Ahh yes sorry, I think I just saw the first half of your comment in the email and missed the second half
